//-------------------------------------------------------------------------------------------------
//HEADER
//-------------------------------------------------------------------------------------------------
#include "Shengming.h"
//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
//CLASS_OF_MY_WORK
//-------------------------------------------------------------------------------------------------
//INSTANCE
MyWork mWORK;
//CREATE
MyWork::MyWork( void )
{
}
//INIT
BOOL MyWork::Init( void )
{
	int index01;

	for( index01 = 0 ; index01 < 256 ; index01++ )
	{
		W_FUNCTION[index01].PROC = NULL;
	}
	//W_LOGIN_SEND
	mWorkerPacketSize[P_LOGIN_SEND] = S_LOGIN_SEND;
	W_FUNCTION[P_LOGIN_SEND].PROC = W_LOGIN_SEND;
	//W_CLIENT_OK_FOR_LOGIN_SEND
	mWorkerPacketSize[P_CLIENT_OK_FOR_LOGIN_SEND] = S_CLIENT_OK_FOR_LOGIN_SEND;
	W_FUNCTION[P_CLIENT_OK_FOR_LOGIN_SEND].PROC = W_CLIENT_OK_FOR_LOGIN_SEND;
	//W_CREATE_MOUSE_PASSWORD_SEND
	mWorkerPacketSize[P_CREATE_MOUSE_PASSWORD_SEND] = S_CREATE_MOUSE_PASSWORD_SEND;
	W_FUNCTION[P_CREATE_MOUSE_PASSWORD_SEND].PROC = W_CREATE_MOUSE_PASSWORD_SEND;
	//W_CHANGE_MOUSE_PASSWORD_SEND
	mWorkerPacketSize[P_CHANGE_MOUSE_PASSWORD_SEND] = S_CHANGE_MOUSE_PASSWORD_SEND;
	W_FUNCTION[P_CHANGE_MOUSE_PASSWORD_SEND].PROC = W_CHANGE_MOUSE_PASSWORD_SEND;
	//W_LOGIN_MOUSE_PASSWORD_SEND
	mWorkerPacketSize[P_LOGIN_MOUSE_PASSWORD_SEND] = S_LOGIN_MOUSE_PASSWORD_SEND;
	W_FUNCTION[P_LOGIN_MOUSE_PASSWORD_SEND].PROC = W_LOGIN_MOUSE_PASSWORD_SEND;
	//W_LOGIN_SECRET_CARD_SEND
	mWorkerPacketSize[P_LOGIN_SECRET_CARD_SEND] = S_LOGIN_SECRET_CARD_SEND;
	W_FUNCTION[P_LOGIN_SECRET_CARD_SEND].PROC = W_LOGIN_SECRET_CARD_SEND;
	//W_CREATE_AVATAR_SEND
	mWorkerPacketSize[P_CREATE_AVATAR_SEND] = S_CREATE_AVATAR_SEND;
	W_FUNCTION[P_CREATE_AVATAR_SEND].PROC = W_CREATE_AVATAR_SEND;
	//W_DELETE_AVATAR_SEND
	mWorkerPacketSize[P_DELETE_AVATAR_SEND] = S_DELETE_AVATAR_SEND;
	W_FUNCTION[P_DELETE_AVATAR_SEND].PROC = W_DELETE_AVATAR_SEND;
	//W_CHANGE_AVATAR_NAME_SEND
	mWorkerPacketSize[P_CHANGE_AVATAR_NAME_SEND] = S_CHANGE_AVATAR_NAME_SEND;
	W_FUNCTION[P_CHANGE_AVATAR_NAME_SEND].PROC = W_CHANGE_AVATAR_NAME_SEND;
	//W_DEMAND_GIFT_SEND
#if 1
	mWorkerPacketSize[P_DEMAND_GIFT_SEND] = S_DEMAND_GIFT_SEND;
	W_FUNCTION[P_DEMAND_GIFT_SEND].PROC = W_DEMAND_GIFT_SEND;
	//W_WANT_GIFT_SEND
	mWorkerPacketSize[P_WANT_GIFT_SEND] = S_WANT_GIFT_SEND;
	W_FUNCTION[P_WANT_GIFT_SEND].PROC = W_WANT_GIFT_SEND;
#else
	mWorkerPacketSize[P_DEMAND_GIFT_SEND] = S_DEMAND_GIFT_SEND;
	W_FUNCTION[P_DEMAND_GIFT_SEND].PROC = NULL;
	//W_WANT_GIFT_SEND
	mWorkerPacketSize[P_WANT_GIFT_SEND] = S_WANT_GIFT_SEND;
	W_FUNCTION[P_WANT_GIFT_SEND].PROC = NULL;
#endif

	//W_DEMAND_ZONE_SERVER_INFO_1
	mWorkerPacketSize[P_DEMAND_ZONE_SERVER_INFO_1] = S_DEMAND_ZONE_SERVER_INFO_1;
	W_FUNCTION[P_DEMAND_ZONE_SERVER_INFO_1].PROC = W_DEMAND_ZONE_SERVER_INFO_1;
	//W_FAIL_MOVE_ZONE_1_SEND
	mWorkerPacketSize[P_FAIL_MOVE_ZONE_1_SEND] = S_FAIL_MOVE_ZONE_1_SEND;
	W_FUNCTION[P_FAIL_MOVE_ZONE_1_SEND].PROC = W_FAIL_MOVE_ZONE_1_SEND;

	//W_RCMD_WORLD_SEND
	mWorkerPacketSize[P_RECOMMAND_WORLD_SEND] = S_RECOMMAND_WORLD_SEND;
	W_FUNCTION[P_RECOMMAND_WORLD_SEND].PROC = W_RCMD_WORLD_SEND;

	//W_EVENT_ITEM_SEND
	mWorkerPacketSize[P_EVENTITEM] = S_EVENTITEM;
	W_FUNCTION[P_EVENTITEM].PROC = W_EVENT_ITEM_SEND;

	//W_RECIVE_GIFT_SEND
	mWorkerPacketSize[P_RECIVEGIFT] = S_RECIVEGIFT;
	W_FUNCTION[P_RECIVEGIFT].PROC = W_RECIVE_GIFT_SEND;

	return TRUE;
}
//FREE
void MyWork::Free( void )
{
}
//-------------------------------------------------------------------------------------------------
