//-------------------------------------------------------------------------------------------------
//HEADER
//-------------------------------------------------------------------------------------------------
#include "Shengming.h"
//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
//CLASS_OF_MY_WORK
//-------------------------------------------------------------------------------------------------
//INSTANCE
MyWork mWORK;
//CREATE
MyWork::MyWork(void)
{
}
//INIT
BOOL MyWork::Init(void)
{
	int index01;

	for (index01 = 0; index01 < 256; index01++)
	{
		W_FUNCTION[index01].PROC = NULL;
	}
	//W_TEMP_REGISTER_SEND
	mWorkerPacketSize[P_TEMP_REGISTER_SEND] = S_TEMP_REGISTER_SEND;
	W_FUNCTION[P_TEMP_REGISTER_SEND].PROC = W_TEMP_REGISTER_SEND;
	//W_REGISTER_AVATAR_SEND
	mWorkerPacketSize[P_REGISTER_AVATAR_SEND] = S_REGISTER_AVATAR_SEND;
	W_FUNCTION[P_REGISTER_AVATAR_SEND].PROC = W_REGISTER_AVATAR_SEND;
	//W_CLIENT_OK_FOR_ZONE_SEND
	mWorkerPacketSize[P_CLIENT_OK_FOR_ZONE_SEND] = S_CLIENT_OK_FOR_ZONE_SEND;
	W_FUNCTION[P_CLIENT_OK_FOR_ZONE_SEND].PROC = W_CLIENT_OK_FOR_ZONE_SEND;
	//W_AUTO_CHECK_ASK_RECV
	mWorkerPacketSize[P_AUTO_CHECK_ASK_RECV] = S_AUTO_CHECK_ASK_RECV;
	W_FUNCTION[P_AUTO_CHECK_ASK_RECV].PROC = W_AUTO_CHECK_ASK_RECV;
	//W_AVATAR_ACTION_SEND
	mWorkerPacketSize[P_AVATAR_ACTION_SEND] = S_AVATAR_ACTION_SEND;
	W_FUNCTION[P_AVATAR_ACTION_SEND].PROC = W_AVATAR_ACTION_SEND;
	//W_UPDATE_AVATAR_ACTION
	mWorkerPacketSize[P_UPDATE_AVATAR_ACTION] = S_UPDATE_AVATAR_ACTION;
	W_FUNCTION[P_UPDATE_AVATAR_ACTION].PROC = W_UPDATE_AVATAR_ACTION;
	//W_GENERAL_NOTICE_SEND
	mWorkerPacketSize[P_GENERAL_NOTICE_SEND] = S_GENERAL_NOTICE_SEND;
	W_FUNCTION[P_GENERAL_NOTICE_SEND].PROC = W_GENERAL_NOTICE_SEND;
	//W_PROCESS_ATTACK_SEND
	mWorkerPacketSize[P_PROCESS_ATTACK_SEND] = S_PROCESS_ATTACK_SEND;
	W_FUNCTION[P_PROCESS_ATTACK_SEND].PROC = W_PROCESS_ATTACK_SEND;
	//W_PROCESS_DATA_SEND
	mWorkerPacketSize[P_PROCESS_DATA_SEND] = S_PROCESS_DATA_SEND;
	W_FUNCTION[P_PROCESS_DATA_SEND].PROC = W_PROCESS_DATA_SEND;
	//W_DEMAND_ZONE_SERVER_INFO_2
	mWorkerPacketSize[P_DEMAND_ZONE_SERVER_INFO_2] = S_DEMAND_ZONE_SERVER_INFO_2;
	W_FUNCTION[P_DEMAND_ZONE_SERVER_INFO_2].PROC = W_DEMAND_ZONE_SERVER_INFO_2;
	//W_FAIL_MOVE_ZONE_2_SEND
	mWorkerPacketSize[P_FAIL_MOVE_ZONE_2_SEND] = S_FAIL_MOVE_ZONE_2_SEND;
	W_FUNCTION[P_FAIL_MOVE_ZONE_2_SEND].PROC = W_FAIL_MOVE_ZONE_2_SEND;
	//W_USE_HOTKEY_ITEM_SEND
	mWorkerPacketSize[P_USE_HOTKEY_ITEM_SEND] = S_USE_HOTKEY_ITEM_SEND;
	W_FUNCTION[P_USE_HOTKEY_ITEM_SEND].PROC = W_USE_HOTKEY_ITEM_SEND;
	//W_USE_INVENTORY_ITEM_SEND
	mWorkerPacketSize[P_USE_INVENTORY_ITEM_SEND] = S_USE_INVENTORY_ITEM_SEND;
	W_FUNCTION[P_USE_INVENTORY_ITEM_SEND].PROC = W_USE_INVENTORY_ITEM_SEND;
	//W_IMPROVE_ITEM_SEND
	mWorkerPacketSize[P_IMPROVE_ITEM_SEND] = S_IMPROVE_ITEM_SEND;
	W_FUNCTION[P_IMPROVE_ITEM_SEND].PROC = W_IMPROVE_ITEM_SEND;
	//W_ADD_ITEM_SEND
	mWorkerPacketSize[P_ADD_ITEM_SEND] = S_ADD_ITEM_SEND;
	W_FUNCTION[P_ADD_ITEM_SEND].PROC = W_ADD_ITEM_SEND;
	//W_EXCHANGE_ITEM_SEND
	mWorkerPacketSize[P_EXCHANGE_ITEM_SEND] = S_EXCHANGE_ITEM_SEND;
	W_FUNCTION[P_EXCHANGE_ITEM_SEND].PROC = W_EXCHANGE_ITEM_SEND;
	//W_HIGH_ITEM_SEND
	mWorkerPacketSize[P_HIGH_ITEM_SEND] = S_HIGH_ITEM_SEND;
	W_FUNCTION[P_HIGH_ITEM_SEND].PROC = W_HIGH_ITEM_SEND;
	//W_LOW_ITEM_SEND
	mWorkerPacketSize[P_LOW_ITEM_SEND] = S_LOW_ITEM_SEND;
	W_FUNCTION[P_LOW_ITEM_SEND].PROC = W_LOW_ITEM_SEND;
	//W_MAKE_ITEM_SEND
	mWorkerPacketSize[P_MAKE_ITEM_SEND] = S_MAKE_ITEM_SEND;
	W_FUNCTION[P_MAKE_ITEM_SEND].PROC = W_MAKE_ITEM_SEND;
	//W_MAKE_SKILL_SEND
	mWorkerPacketSize[P_MAKE_SKILL_SEND] = S_MAKE_SKILL_SEND;
	W_FUNCTION[P_MAKE_SKILL_SEND].PROC = W_MAKE_SKILL_SEND;
	//W_START_PSHOP_SEND
	mWorkerPacketSize[P_START_PSHOP_SEND] = S_START_PSHOP_SEND;
	W_FUNCTION[P_START_PSHOP_SEND].PROC = W_START_PSHOP_SEND;
	//W_END_PSHOP_SEND
	mWorkerPacketSize[P_END_PSHOP_SEND] = S_END_PSHOP_SEND;
	W_FUNCTION[P_END_PSHOP_SEND].PROC = W_END_PSHOP_SEND;
	//W_DEMAND_PSHOP_SEND
	mWorkerPacketSize[P_DEMAND_PSHOP_SEND] = S_DEMAND_PSHOP_SEND;
	W_FUNCTION[P_DEMAND_PSHOP_SEND].PROC = W_DEMAND_PSHOP_SEND;
	//W_PSHOP_ITEM_INFO_SEND
	mWorkerPacketSize[P_PSHOP_ITEM_INFO_SEND] = S_PSHOP_ITEM_INFO_SEND;
	W_FUNCTION[P_PSHOP_ITEM_INFO_SEND].PROC = W_PSHOP_ITEM_INFO_SEND;
	//W_BUY_PSHOP_SEND
	mWorkerPacketSize[P_BUY_PSHOP_SEND] = S_BUY_PSHOP_SEND;
	W_FUNCTION[P_BUY_PSHOP_SEND].PROC = W_BUY_PSHOP_SEND;
	//W_PROCESS_QUEST_SEND
	mWorkerPacketSize[P_PROCESS_QUEST_SEND] = S_PROCESS_QUEST_SEND;
	W_FUNCTION[P_PROCESS_QUEST_SEND].PROC = W_PROCESS_QUEST_SEND;
	//W_CHANGE_TO_TRIBE4_SEND
	mWorkerPacketSize[P_CHANGE_TO_TRIBE4_SEND] = S_CHANGE_TO_TRIBE4_SEND;
	W_FUNCTION[P_CHANGE_TO_TRIBE4_SEND].PROC = W_CHANGE_TO_TRIBE4_SEND;
	//W_GENERAL_CHAT_SEND
	mWorkerPacketSize[P_GENERAL_CHAT_SEND] = S_GENERAL_CHAT_SEND;
	W_FUNCTION[P_GENERAL_CHAT_SEND].PROC = W_GENERAL_CHAT_SEND;
	//W_SECRET_CHAT_SEND
	mWorkerPacketSize[P_SECRET_CHAT_SEND] = S_SECRET_CHAT_SEND;
	W_FUNCTION[P_SECRET_CHAT_SEND].PROC = W_SECRET_CHAT_SEND;
	//W_GENERAL_SHOUT_SEND
	mWorkerPacketSize[P_GENERAL_SHOUT_SEND] = S_GENERAL_SHOUT_SEND;
	W_FUNCTION[P_GENERAL_SHOUT_SEND].PROC = W_GENERAL_SHOUT_SEND;
	//W_GET_CASH_SIZE_SEND
	mWorkerPacketSize[P_GET_CASH_SIZE_SEND] = S_GET_CASH_SIZE_SEND;
	W_FUNCTION[P_GET_CASH_SIZE_SEND].PROC = W_GET_CASH_SIZE_SEND;
	//W_BUY_CASH_ITEM_SEND
	mWorkerPacketSize[P_BUY_CASH_ITEM_SEND] = S_BUY_CASH_ITEM_SEND;
	W_FUNCTION[P_BUY_CASH_ITEM_SEND].PROC = W_BUY_CASH_ITEM_SEND;
	//W_DUEL_ASK_SEND
	mWorkerPacketSize[P_DUEL_ASK_SEND] = S_DUEL_ASK_SEND;
	W_FUNCTION[P_DUEL_ASK_SEND].PROC = W_DUEL_ASK_SEND;
	//W_DUEL_CANCEL_SEND
	mWorkerPacketSize[P_DUEL_CANCEL_SEND] = S_DUEL_CANCEL_SEND;
	W_FUNCTION[P_DUEL_CANCEL_SEND].PROC = W_DUEL_CANCEL_SEND;
	//W_DUEL_ANSWER_SEND
	mWorkerPacketSize[P_DUEL_ANSWER_SEND] = S_DUEL_ANSWER_SEND;
	W_FUNCTION[P_DUEL_ANSWER_SEND].PROC = W_DUEL_ANSWER_SEND;
	//W_DUEL_START_SEND
	mWorkerPacketSize[P_DUEL_START_SEND] = S_DUEL_START_SEND;
	W_FUNCTION[P_DUEL_START_SEND].PROC = W_DUEL_START_SEND;
	//W_TRADE_ASK_SEND
	mWorkerPacketSize[P_TRADE_ASK_SEND] = S_TRADE_ASK_SEND;
	W_FUNCTION[P_TRADE_ASK_SEND].PROC = W_TRADE_ASK_SEND;
	//W_TRADE_CANCEL_SEND
	mWorkerPacketSize[P_TRADE_CANCEL_SEND] = S_TRADE_CANCEL_SEND;
	W_FUNCTION[P_TRADE_CANCEL_SEND].PROC = W_TRADE_CANCEL_SEND;
	//W_TRADE_ANSWER_SEND
	mWorkerPacketSize[P_TRADE_ANSWER_SEND] = S_TRADE_ANSWER_SEND;
	W_FUNCTION[P_TRADE_ANSWER_SEND].PROC = W_TRADE_ANSWER_SEND;
	//W_TRADE_START_SEND
	mWorkerPacketSize[P_TRADE_START_SEND] = S_TRADE_START_SEND;
	W_FUNCTION[P_TRADE_START_SEND].PROC = W_TRADE_START_SEND;
	//W_TRADE_MENU_SEND
	mWorkerPacketSize[P_TRADE_MENU_SEND] = S_TRADE_MENU_SEND;
	W_FUNCTION[P_TRADE_MENU_SEND].PROC = W_TRADE_MENU_SEND;
	//W_TRADE_END_SEND
	mWorkerPacketSize[P_TRADE_END_SEND] = S_TRADE_END_SEND;
	W_FUNCTION[P_TRADE_END_SEND].PROC = W_TRADE_END_SEND;
	//W_FRIEND_ASK_SEND
	mWorkerPacketSize[P_FRIEND_ASK_SEND] = S_FRIEND_ASK_SEND;
	W_FUNCTION[P_FRIEND_ASK_SEND].PROC = W_FRIEND_ASK_SEND;
	//W_FRIEND_CANCEL_SEND
	mWorkerPacketSize[P_FRIEND_CANCEL_SEND] = S_FRIEND_CANCEL_SEND;
	W_FUNCTION[P_FRIEND_CANCEL_SEND].PROC = W_FRIEND_CANCEL_SEND;
	//W_FRIEND_ANSWER_SEND
	mWorkerPacketSize[P_FRIEND_ANSWER_SEND] = S_FRIEND_ANSWER_SEND;
	W_FUNCTION[P_FRIEND_ANSWER_SEND].PROC = W_FRIEND_ANSWER_SEND;
	//W_FRIEND_MAKE_SEND
	mWorkerPacketSize[P_FRIEND_MAKE_SEND] = S_FRIEND_MAKE_SEND;
	W_FUNCTION[P_FRIEND_MAKE_SEND].PROC = W_FRIEND_MAKE_SEND;
	//W_FRIEND_FIND_SEND
	mWorkerPacketSize[P_FRIEND_FIND_SEND] = S_FRIEND_FIND_SEND;
	W_FUNCTION[P_FRIEND_FIND_SEND].PROC = W_FRIEND_FIND_SEND;
	//W_FRIEND_DELETE_SEND
	mWorkerPacketSize[P_FRIEND_DELETE_SEND] = S_FRIEND_DELETE_SEND;
	W_FUNCTION[P_FRIEND_DELETE_SEND].PROC = W_FRIEND_DELETE_SEND;
	//W_TEACHER_ASK_SEND
	mWorkerPacketSize[P_TEACHER_ASK_SEND] = S_TEACHER_ASK_SEND;
	W_FUNCTION[P_TEACHER_ASK_SEND].PROC = W_TEACHER_ASK_SEND;
	//W_TEACHER_CANCEL_SEND
	mWorkerPacketSize[P_TEACHER_CANCEL_SEND] = S_TEACHER_CANCEL_SEND;
	W_FUNCTION[P_TEACHER_CANCEL_SEND].PROC = W_TEACHER_CANCEL_SEND;
	//W_TEACHER_ANSWER_SEND
	mWorkerPacketSize[P_TEACHER_ANSWER_SEND] = S_TEACHER_ANSWER_SEND;
	W_FUNCTION[P_TEACHER_ANSWER_SEND].PROC = W_TEACHER_ANSWER_SEND;
	//W_TEACHER_START_SEND
	mWorkerPacketSize[P_TEACHER_START_SEND] = S_TEACHER_START_SEND;
	W_FUNCTION[P_TEACHER_START_SEND].PROC = W_TEACHER_START_SEND;
	//W_TEACHER_END_SEND
	mWorkerPacketSize[P_TEACHER_END_SEND] = S_TEACHER_END_SEND;
	W_FUNCTION[P_TEACHER_END_SEND].PROC = W_TEACHER_END_SEND;
	//W_TEACHER_STATE_SEND
	mWorkerPacketSize[P_TEACHER_STATE_SEND] = S_TEACHER_STATE_SEND;
	W_FUNCTION[P_TEACHER_STATE_SEND].PROC = W_TEACHER_STATE_SEND;
	//W_PARTY_ASK_SEND
	mWorkerPacketSize[P_PARTY_ASK_SEND] = S_PARTY_ASK_SEND;
	W_FUNCTION[P_PARTY_ASK_SEND].PROC = W_PARTY_ASK_SEND;
	//W_PARTY_CANCEL_SEND
	mWorkerPacketSize[P_PARTY_CANCEL_SEND] = S_PARTY_CANCEL_SEND;
	W_FUNCTION[P_PARTY_CANCEL_SEND].PROC = W_PARTY_CANCEL_SEND;
	//W_PARTY_ANSWER_SEND
	mWorkerPacketSize[P_PARTY_ANSWER_SEND] = S_PARTY_ANSWER_SEND;
	W_FUNCTION[P_PARTY_ANSWER_SEND].PROC = W_PARTY_ANSWER_SEND;
	//W_PARTY_CHAT_SEND
	mWorkerPacketSize[P_PARTY_CHAT_SEND] = S_PARTY_CHAT_SEND;
	W_FUNCTION[P_PARTY_CHAT_SEND].PROC = W_PARTY_CHAT_SEND;
	//W_PARTY_LEAVE_SEND
	mWorkerPacketSize[P_PARTY_LEAVE_SEND] = S_PARTY_LEAVE_SEND;
	W_FUNCTION[P_PARTY_LEAVE_SEND].PROC = W_PARTY_LEAVE_SEND;
	//W_PARTY_EXILE_SEND
	mWorkerPacketSize[P_PARTY_EXILE_SEND] = S_PARTY_EXILE_SEND;
	W_FUNCTION[P_PARTY_EXILE_SEND].PROC = W_PARTY_EXILE_SEND;
	//W_PARTY_BREAK_SEND
	mWorkerPacketSize[P_PARTY_BREAK_SEND] = S_PARTY_BREAK_SEND;
	W_FUNCTION[P_PARTY_BREAK_SEND].PROC = W_PARTY_BREAK_SEND;
	//W_GUILD_ASK_SEND
	mWorkerPacketSize[P_GUILD_ASK_SEND] = S_GUILD_ASK_SEND;
	W_FUNCTION[P_GUILD_ASK_SEND].PROC = W_GUILD_ASK_SEND;
	//W_GUILD_CANCEL_SEND
	mWorkerPacketSize[P_GUILD_CANCEL_SEND] = S_GUILD_CANCEL_SEND;
	W_FUNCTION[P_GUILD_CANCEL_SEND].PROC = W_GUILD_CANCEL_SEND;
	//W_GUILD_ANSWER_SEND
	mWorkerPacketSize[P_GUILD_ANSWER_SEND] = S_GUILD_ANSWER_SEND;
	W_FUNCTION[P_GUILD_ANSWER_SEND].PROC = W_GUILD_ANSWER_SEND;
	//W_GUILD_WORK_SEND
	mWorkerPacketSize[P_GUILD_WORK_SEND] = S_GUILD_WORK_SEND;
	W_FUNCTION[P_GUILD_WORK_SEND].PROC = W_GUILD_WORK_SEND;
	//W_GUILD_NOTICE_SEND
	mWorkerPacketSize[P_GUILD_NOTICE_SEND] = S_GUILD_NOTICE_SEND;
	W_FUNCTION[P_GUILD_NOTICE_SEND].PROC = W_GUILD_NOTICE_SEND;
	//W_GUILD_CHAT_SEND
	mWorkerPacketSize[P_GUILD_CHAT_SEND] = S_GUILD_CHAT_SEND;
	W_FUNCTION[P_GUILD_CHAT_SEND].PROC = W_GUILD_CHAT_SEND;
	//W_GUILD_FIND_SEND
	mWorkerPacketSize[P_GUILD_FIND_SEND] = S_GUILD_FIND_SEND;
	W_FUNCTION[P_GUILD_FIND_SEND].PROC = W_GUILD_FIND_SEND;
	//W_TRIBE_WORK_SEND
	mWorkerPacketSize[P_TRIBE_WORK_SEND] = S_TRIBE_WORK_SEND;
	W_FUNCTION[P_TRIBE_WORK_SEND].PROC = W_TRIBE_WORK_SEND;
	//W_TRIBE_NOTICE_SEND
	mWorkerPacketSize[P_TRIBE_NOTICE_SEND] = S_TRIBE_NOTICE_SEND;
	W_FUNCTION[P_TRIBE_NOTICE_SEND].PROC = W_TRIBE_NOTICE_SEND;
	//W_TRIBE_CHAT_SEND
	mWorkerPacketSize[P_TRIBE_CHAT_SEND] = S_TRIBE_CHAT_SEND;
	W_FUNCTION[P_TRIBE_CHAT_SEND].PROC = W_TRIBE_CHAT_SEND;
	//W_TRIBE_BANK_SEND
	mWorkerPacketSize[P_TRIBE_BANK_SEND] = S_TRIBE_BANK_SEND;
	W_FUNCTION[P_TRIBE_BANK_SEND].PROC = W_TRIBE_BANK_SEND;
	//W_TRIBE_VOTE_SEND
	mWorkerPacketSize[P_TRIBE_VOTE_SEND] = S_TRIBE_VOTE_SEND;
	W_FUNCTION[P_TRIBE_VOTE_SEND].PROC = W_TRIBE_VOTE_SEND;
	//W_CRAFT
	mWorkerPacketSize[P_CRAFT] = S_CRAFT;
	W_FUNCTION[P_CRAFT].PROC = W_CRAFT;
	//W_FUNCITON_NOTICE
	mWorkerPacketSize[P_FUNCITON_NOTICE] = S_FUNCITON_NOTICE;
	W_FUNCTION[P_FUNCITON_NOTICE].PROC = W_FUNCITON_NOTICE;
	//W_AUTOHUNT
	mWorkerPacketSize[P_AUTOHUNT] = S_AUTOHUNT;
	W_FUNCTION[P_AUTOHUNT].PROC = W_AUTOHUNT;
	//W_DAILY_MISSION
	mWorkerPacketSize[P_DAILY_MISSION] = S_DAILY_MISSION;
	W_FUNCTION[P_DAILY_MISSION].PROC = W_DAILY_MISSION;
	//W_RANK
	mWorkerPacketSize[P_RANK] = S_RANK;
	W_FUNCTION[P_RANK].PROC = W_RANK;
	//W_SOCKETSYSTEM
	mWorkerPacketSize[P_SOCKET_RECV] = S_SOCKET_RECV;
	W_FUNCTION[P_SOCKET_RECV].PROC = W_SOCKETSYSTEM;
	//W_ADDSOCKETSYSTEM
	mWorkerPacketSize[P_Socket2Item] = S_Socket2Item;
	W_FUNCTION[P_Socket2Item].PROC = W_ADDSOCKETSYSTEM;
	//W_ADDSOCKETSYSTEM
	mWorkerPacketSize[P_UPRADGETOWER] = S_UPRADGETOWER;
	W_FUNCTION[P_UPRADGETOWER].PROC = W_UPRADGETOWER;
	//W_ANIMAL_STATE_SEND
	mWorkerPacketSize[P_ANIMAL_STATE_SEND] = S_ANIMAL_STATE_SEND;
	W_FUNCTION[P_ANIMAL_STATE_SEND].PROC = W_ANIMAL_STATE_SEND;
	//W_AUTO_POT
	mWorkerPacketSize[P_AUTO_POT] = S_AUTO_POT;
	W_FUNCTION[P_AUTO_POT].PROC = W_AUTO_POT;
	//w_MOUT_ABSORB
	mWorkerPacketSize[P_MOUT_ABSORB] = S_MOUT_ABSORB;
	W_FUNCTION[P_MOUT_ABSORB].PROC = w_MOUT_ABSORB;
	//W_COSTUME
	mWorkerPacketSize[P_COSTUME] = S_COSTUME;
	W_FUNCTION[P_COSTUME].PROC = W_COSTUME;
	//W_AUTOBUFF
	mWorkerPacketSize[P_AUTOBUFF] = S_AUTOBUFF;
	W_FUNCTION[P_AUTOBUFF].PROC = W_AUTOBUFF;
	//W_AUTOBUFF1
	mWorkerPacketSize[P_AUTOBUFF1] = S_AUTOBUFF1;
	W_FUNCTION[P_AUTOBUFF1].PROC = W_AUTOBUFF1;
	//W_MUHAFIZ
	mWorkerPacketSize[P_MUHAFIZ] = S_MUHAFIZ;
	W_FUNCTION[P_MUHAFIZ].PROC = W_MUHAFIZ;
	//W_RANKPRİZE
	mWorkerPacketSize[P_RANKPRIZE] = S_RANKPRIZE;
	W_FUNCTION[P_RANKPRIZE].PROC = W_RANKPRIZE;
	//W_KAPSUL
	mWorkerPacketSize[P_KAPSUL] = S_KAPSUL;
	W_FUNCTION[P_KAPSUL].PROC = W_KAPSUL;
	//W_RANKSYSTEM
	mWorkerPacketSize[P_RankSystem] = S_RankSystem;
	W_FUNCTION[P_RankSystem].PROC = W_RANKSYSTEM;
	//W_HIDECOSTUME
	mWorkerPacketSize[P_HideCostume] = S_HideCostume;
	W_FUNCTION[P_HideCostume].PROC = W_HIDECOSTUME;
	//W_BOTTLE
	mWorkerPacketSize[P_BOTTLE] = S_BOTTLE;
	W_FUNCTION[P_BOTTLE].PROC = W_BOTTLE;
	//W_BOTTLE
	mWorkerPacketSize[P_LEGIMPROVE] = S_LEGIMPROVE;
	W_FUNCTION[P_LEGIMPROVE].PROC = W_LEGENDERYIMPROVE;
	//W_GET_CASH_ITEM_INFO_SEND
	mWorkerPacketSize[P_GET_CASH_ITEM_INFO_SEND] = S_GET_CASH_ITEM_INFO_SEND;
	W_FUNCTION[P_GET_CASH_ITEM_INFO_SEND].PROC = W_GET_CASH_ITEM_INFO_SEND;
	//W_VALETSHOPSEND
	//mWorkerPacketSize[P_VALETSHOPOPEN] = S_VALETSHOPOPEN;
	//W_FUNCTION[P_VALETSHOPOPEN].PROC = W_VALETSHOPSEND;
	//W_VALETSHOPITEMDEL
	//mWorkerPacketSize[P_VALETSHOPITEMDEL] = S_VALETSHOPITEMDEL;
	//W_FUNCTION[P_VALETSHOPITEMDEL].PROC = W_VALETSHOPITEMDEL;
	//W_VALETSHOPSEND
	//mWorkerPacketSize[P_VALETSHOPGETMONEY] = S_VALETSHOPGETMONEY;
	//W_FUNCTION[P_VALETSHOPGETMONEY].PROC = W_VALET_SHOP_GET_ITEM;
	//W_FISHING
	mWorkerPacketSize[P_FISHING] = S_FISHING;
	W_FUNCTION[P_FISHING].PROC = W_FISHING;
	//W_FISHING2
	mWorkerPacketSize[P_FISHING2] = S_FISHING2;
	W_FUNCTION[P_FISHING2].PROC = W_FISHING2;
	//W_FISHINGWINITEM
	mWorkerPacketSize[P_WINFISH] = S_WINFISH;
	W_FUNCTION[P_WINFISH].PROC = W_FISHINGWINITEM;
	//W_BLOODMAERKET
	mWorkerPacketSize[P_BLOODMARKET] = S_BLOODMARKET;
	W_FUNCTION[P_BLOODMARKET].PROC = W_BLOODMAERKET;
	//W_BLOODMAERKETBUY
	mWorkerPacketSize[P_BLOODMARKETBUY] = S_BLOODMARKETBUY;
	W_FUNCTION[P_BLOODMARKETBUY].PROC = W_BLOODMAERKETBUY;
	//W_BLOODMAERKETBUY
	mWorkerPacketSize[P_SKILLCOMBINE] = S_SKILLCOMBINE;
	W_FUNCTION[P_SKILLCOMBINE].PROC = W_SKILLCOMBINE;
	//W_TIMEEFFECT
	mWorkerPacketSize[P_TIME_EFFEECT] = S_TIME_EFFEECT;
	W_FUNCTION[P_TIME_EFFEECT].PROC = W_TIMEEFFECT;
	//W_DESTROY_ITEM
	mWorkerPacketSize[P_DESTROY_ITEM] = S_DESTROY_ITEM;
	W_FUNCTION[P_DESTROY_ITEM].PROC = W_DESTROY_ITEM;
	//W_PET_COMBINE_SEND
	mWorkerPacketSize[P_PET_COMBINE] = S_PET_COMBINE;
	W_FUNCTION[P_PET_COMBINE].PROC = W_PET_COMBINE_SEND;
	//W_CAPE_UPGRADE
	mWorkerPacketSize[P_UPGRADE_CAPE_SEND] = S_UPGRADE_CAPE_SEND;
	W_FUNCTION[P_UPGRADE_CAPE_SEND].PROC = W_CAPE_UPGRADE;
	//W_TAILOR_SEAL
	mWorkerPacketSize[P_TAILOR_SEAL] = S_TAILOR_SEAL;
	W_FUNCTION[P_TAILOR_SEAL].PROC = W_TAILOR_SEAL;
	//W_FURY
	mWorkerPacketSize[P_FURY] = S_FURY;
	W_FUNCTION[P_FURY].PROC = W_FURY;
	//W_TRADER_WARLORD_UPGRADE
	mWorkerPacketSize[P_TRADER_WARLORD_UPGRADE] = S_TRADER_WARLORD_UPGRADE;
	W_FUNCTION[P_TRADER_WARLORD_UPGRADE].PROC = W_TRADER_WARLORD_UPGRADE;

	mWorkerPacketSize[P_BEGGARADDABILITY] = S_BEGGARADDABILITY;
	W_FUNCTION[P_BEGGARADDABILITY].PROC = W_BEGGARADDABILITY;

	mWorkerPacketSize[P_ENGRAVE] = S_ENGRAVE;
	W_FUNCTION[P_ENGRAVE].PROC = W_ENGRAVE;

	mWorkerPacketSize[P_TAILOR_ITEM_UPGRADE] = S_TAILOR_ITEM_UPGRADE;
	W_FUNCTION[P_TAILOR_ITEM_UPGRADE].PROC = W_TAILOR_ITEM_UPGRADE;

	return TRUE;
}
//FREE
void MyWork::Free(void)
{
}
//-------------------------------------------------------------------------------------------------