//-------------------------------------------------------------------------------------------------
//HEADER
//-------------------------------------------------------------------------------------------------
#include "Shengming.h"
//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
//CLASS_OF_MY_WORK
//-------------------------------------------------------------------------------------------------
//INSTANCE
MyWork mWORK;
//CREATE
MyWork::MyWork( void )
{
}
//INIT
BOOL MyWork::Init( void )
{
	int index01;

	for( index01 = 0 ; index01 < 256 ; index01++ )
	{
		W_FUNCTION[index01].PROC = NULL;
	}
	//-------------//
	//LOGIN->CENTER//
	//-------------//
	//W_LOGIN_FOR_CENTER_SEND
	mWorkerPacketSize[P_LOGIN_FOR_CENTER_SEND] = S_LOGIN_FOR_CENTER_SEND;
	W_FUNCTION[P_LOGIN_FOR_CENTER_SEND].PROC = W_LOGIN_FOR_CENTER_SEND;
	//W_LOGIN_OK_FOR_CENTER_SEND
	mWorkerPacketSize[P_LOGIN_OK_FOR_CENTER_SEND] = S_LOGIN_OK_FOR_CENTER_SEND;
	W_FUNCTION[P_LOGIN_OK_FOR_CENTER_SEND].PROC = W_LOGIN_OK_FOR_CENTER_SEND;
	//W_GET_ZONE_SERVER_INFO_1
	mWorkerPacketSize[P_GET_ZONE_SERVER_INFO_1] = S_GET_ZONE_SERVER_INFO_1;
	W_FUNCTION[P_GET_ZONE_SERVER_INFO_1].PROC = W_GET_ZONE_SERVER_INFO_1;

	mWorkerPacketSize[LTOG_BAN_PLAYER_TYPE] = LTOG_BAN_PLAYER_SIZE;
	W_FUNCTION[LTOG_BAN_PLAYER_TYPE].PROC = W_BAN_PLAYER;
	//------------//
	//ZONE->CENTER//
	//------------//
	//W_ZONE_FOR_CENTER_SEND
	mWorkerPacketSize[P_ZONE_FOR_CENTER_SEND] = S_ZONE_FOR_CENTER_SEND;
	W_FUNCTION[P_ZONE_FOR_CENTER_SEND].PROC = W_ZONE_FOR_CENTER_SEND;
	//W_ZONE_OK_FOR_CENTER_SEND
	mWorkerPacketSize[P_ZONE_OK_FOR_CENTER_SEND] = S_ZONE_OK_FOR_CENTER_SEND;
	W_FUNCTION[P_ZONE_OK_FOR_CENTER_SEND].PROC = W_ZONE_OK_FOR_CENTER_SEND;
	//W_DEMAND_BROADCAST_INFO
	mWorkerPacketSize[P_DEMAND_BROADCAST_INFO] = S_DEMAND_BROADCAST_INFO;
	W_FUNCTION[P_DEMAND_BROADCAST_INFO].PROC = W_DEMAND_BROADCAST_INFO;
	//W_SERCH_AVATAR_SEND
	mWorkerPacketSize[P_SERCH_AVATAR_SEND] = S_SERCH_AVATAR_SEND;
	W_FUNCTION[P_SERCH_AVATAR_SEND].PROC = W_SERCH_AVATAR_SEND;
	//W_CHECK_EVENT_SEND
	mWorkerPacketSize[P_CHECK_EVENT_SEND] = S_CHECK_EVENT_SEND;
	W_FUNCTION[P_CHECK_EVENT_SEND].PROC = W_CHECK_EVENT_SEND;
	//W_GET_TOTAL_RANK_INFO
	mWorkerPacketSize[P_GET_TOTAL_RANK_INFO_SEND] = S_GET_TOTAL_RANK_INFO_SEND;
	W_FUNCTION[P_GET_TOTAL_RANK_INFO_SEND].PROC = W_GET_TOTAL_RANK_INFO_SEND;
	//W_GET_RANK_INFO
	mWorkerPacketSize[P_GET_RANK_INFO_SEND] = S_GET_RANK_INFO_SEND;
	W_FUNCTION[P_GET_RANK_INFO_SEND].PROC = W_GET_RANK_INFO_SEND;
	//W_ZONE_FOR_CENTER_CONNECTION_SEND
	mWorkerPacketSize[P_ZONE_CONNECTION_INFO_SEND] = S_ZONE_CONNECTION_INFO_SEND;
	W_FUNCTION[P_ZONE_CONNECTION_INFO_SEND].PROC = W_ZONE_FOR_CENTER_CONNECTION_SEND;
    // @ Cost Info Download @
    //W_UPDATE_CASH_ITEM_INFO_FOR_CENTER
    mWorkerPacketSize[P_UPDATE_CASH_ITEM_INFO_FOR_CENTER] = S_UPDATE_CASH_ITEM_INFO_FOR_CENTER;
    W_FUNCTION[P_UPDATE_CASH_ITEM_INFO_FOR_CENTER].PROC = W_UPDATE_CASH_ITEM_INFO_FOR_CENTER;
    // @

	//------------//
	//TOOL->CENTER//
	//------------//
	//W_TOOL_FOR_CENTER_SEND
	mWorkerPacketSize[P_TOOL_FOR_CENTER_SEND] = S_TOOL_FOR_CENTER_SEND;
	W_FUNCTION[P_TOOL_FOR_CENTER_SEND].PROC = W_TOOL_FOR_CENTER_SEND;
	//W_TOOL_OK_FOR_CENTER_SEND
	mWorkerPacketSize[P_TOOL_OK_FOR_CENTER_SEND] = S_TOOL_OK_FOR_CENTER_SEND;
	W_FUNCTION[P_TOOL_OK_FOR_CENTER_SEND].PROC = W_TOOL_OK_FOR_CENTER_SEND;
	//W_DEMAND_START_FOR_TOOL
	mWorkerPacketSize[P_DEMAND_START_FOR_TOOL] = S_DEMAND_START_FOR_TOOL;
	W_FUNCTION[P_DEMAND_START_FOR_TOOL].PROC = W_DEMAND_START_FOR_TOOL;
	//W_DEMAND_NOTICE_FOR_TOOL
	mWorkerPacketSize[P_DEMAND_NOTICE_FOR_TOOL] = S_DEMAND_NOTICE_FOR_TOOL;
	W_FUNCTION[P_DEMAND_NOTICE_FOR_TOOL].PROC = W_DEMAND_NOTICE_FOR_TOOL;
	//W_DEMAND_SET_EVENT_FOR_TOOL
	mWorkerPacketSize[P_DEMAND_SET_EVENT_FOR_TOOL] = S_DEMAND_SET_EVENT_FOR_TOOL;
	W_FUNCTION[P_DEMAND_SET_EVENT_FOR_TOOL].PROC = W_DEMAND_SET_EVENT_FOR_TOOL;
	//W_DEMAND_SHUTDOWN_FOR_TOOL
	mWorkerPacketSize[P_DEMAND_SHUTDOWN_FOR_TOOL] = S_DEMAND_SHUTDOWN_FOR_TOOL;
	W_FUNCTION[P_DEMAND_SHUTDOWN_FOR_TOOL].PROC = W_DEMAND_SHUTDOWN_FOR_TOOL;
	//W_DEMAND_SET_GM_ORDER_FOR_GMTOOL
	mWorkerPacketSize[P_DEMAND_SET_GM_ORDER_FOR_GMTOOL] = S_DEMAND_SET_GM_ORDER_FOR_GMTOOL;
	W_FUNCTION[P_DEMAND_SET_GM_ORDER_FOR_GMTOOL].PROC = W_DEMAND_SET_GM_ORDER_FOR_GMTOOL;	
	//W_DEMAND_SERCH_AVATAR_FOR_GMTOOL
	mWorkerPacketSize[P_DEMAND_SERCH_AVATAR_FOR_GMTOOL] = S_DEMAND_SERCH_AVATAR_FOR_GMTOOL;
	W_FUNCTION[P_DEMAND_SERCH_AVATAR_FOR_GMTOOL].PROC = W_DEMAND_SERCH_AVATAR_FOR_GMTOOL;	
	//W_DEMAND_SET_GM_ORDER_FOR_GMTOOL
	mWorkerPacketSize[P_DEMAND_SET_GM_ORDER_FOR_GMTOOL_MOVE_AVATAR] = S_DEMAND_SET_GM_ORDER_FOR_GMTOOL_MOVE_AVATAR;
	W_FUNCTION[P_DEMAND_SET_GM_ORDER_FOR_GMTOOL_MOVE_AVATAR].PROC = W_DEMAND_SET_GM_ORDER_FOR_GMTOOL_MOVE_AVATAR;		
	//W_DEMAND_CHECK_EVENT_FOR_TOOL
	mWorkerPacketSize[P_DEMAND_CHECK_EVENT_FOR_TOOL] = S_DEMAND_CHECK_EVENT_FOR_TOOL;
	W_FUNCTION[P_DEMAND_CHECK_EVENT_FOR_TOOL].PROC = W_DEMAND_CHECK_EVENT_FOR_TOOL;
	//-----------------------//
	//[CHAT_TOOL] -> [CENTER]//
	//-----------------------//
	//W_CHAT_TOOL_FOR_CENTER_SEND
	mWorkerPacketSize[P_CHAT_TOOL_FOR_CENTER_SEND] = S_CHAT_TOOL_FOR_CENTER_SEND;
	W_FUNCTION[P_CHAT_TOOL_FOR_CENTER_SEND].PROC = W_CHAT_TOOL_FOR_CENTER_SEND;
	//W_CHAT_TOOL_OK_FOR_CENTER_SEND
	mWorkerPacketSize[P_CHAT_TOOL_OK_FOR_CENTER_SEND] = S_CHAT_TOOL_OK_FOR_CENTER_SEND;
	W_FUNCTION[P_CHAT_TOOL_OK_FOR_CENTER_SEND].PROC = W_CHAT_TOOL_OK_FOR_CENTER_SEND;
	//W_TRIBE_CHAT_FOR_CHAT_TOOL_SEND
	mWorkerPacketSize[P_TRIBE_CHAT_FOR_CHAT_TOOL_SEND] = S_TRIBE_CHAT_FOR_CHAT_TOOL_SEND;
	W_FUNCTION[P_TRIBE_CHAT_FOR_CHAT_TOOL_SEND].PROC = W_TRIBE_CHAT_FOR_CHAT_TOOL_SEND;
	//W_SECRET_CHAT_FOR_CHAT_TOOL_SEND
	mWorkerPacketSize[P_SECRET_CHAT_FOR_CHAT_TOOL_SEND] = S_SECRET_CHAT_FOR_CHAT_TOOL_SEND;
	W_FUNCTION[P_SECRET_CHAT_FOR_CHAT_TOOL_SEND].PROC = W_SECRET_CHAT_FOR_CHAT_TOOL_SEND;
	//--------------------//
	//[POLICE] -> [CENTER]//
	//--------------------//
	//W_POLICE_FOR_CENTER_SEND
	mWorkerPacketSize[P_POLICE_FOR_CENTER_SEND] = S_POLICE_FOR_CENTER_SEND;
	W_FUNCTION[P_POLICE_FOR_CENTER_SEND].PROC = W_POLICE_FOR_CENTER_SEND;
	//W_POLICE_OK_FOR_CENTER_SEND
	mWorkerPacketSize[P_POLICE_OK_FOR_CENTER_SEND] = S_POLICE_OK_FOR_CENTER_SEND;
	W_FUNCTION[P_POLICE_OK_FOR_CENTER_SEND].PROC = W_POLICE_OK_FOR_CENTER_SEND;
	//W_POLICE_INFO_FOR_CENTER_SEND
	mWorkerPacketSize[P_POLICE_INFO_FOR_CENTER_SEND] = S_POLICE_INFO_FOR_CENTER_SEND;
	W_FUNCTION[P_POLICE_INFO_FOR_CENTER_SEND].PROC = W_POLICE_INFO_FOR_CENTER_SEND;
    // # X-Trap # {
    
    // # }
	return TRUE;
}
//FREE
void MyWork::Free( void )
{
}
//-------------------------------------------------------------------------------------------------
